<?php
//CMS cache file, DO NOT modify me!
//Created on July 16, 2010, 12:19

$CONTENT_MODEL_INFO = array (
  1 => 
  array (
    'TableID' => '1',
    'Name' => '新闻系统模型',
    'DSNID' => '1',
    'TitleField' => 'Title',
    'Model' => 
    array (
      0 => 
      array (
        'ContentFieldID' => '1',
        'TableID' => '1',
        'FieldTitle' => '标题',
        'FieldName' => 'Title',
        'FieldType' => 'varchar',
        'FieldSize' => '250',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => 'unique',
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => '新闻的标题',
        'FieldOrder' => '0',
        'FieldListDisplay' => '1',
        'IsMainField' => '0',
        'IsTitleField' => '1',
        'FieldSearchable' => '1',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      1 => 
      array (
        'ContentFieldID' => '62',
        'TableID' => '1',
        'FieldTitle' => '文章关键标识扩展',
        'FieldName' => 'ext_key',
        'FieldType' => 'varchar',
        'FieldSize' => '250',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '0',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      2 => 
      array (
        'ContentFieldID' => '10',
        'TableID' => '1',
        'FieldTitle' => '标题颜色',
        'FieldName' => 'TitleColor',
        'FieldType' => 'varchar',
        'FieldSize' => '7',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => 'color',
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '1',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '0',
        'EnableCollection' => '0',
        'EnablePublish' => '1',
      ),
      3 => 
      array (
        'ContentFieldID' => '2',
        'TableID' => '1',
        'FieldTitle' => '作者',
        'FieldName' => 'Author',
        'FieldType' => 'varchar',
        'FieldSize' => '20',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => '新闻的原作者',
        'FieldOrder' => '2',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '0',
        'EnableCollection' => '0',
        'EnablePublish' => '0',
      ),
      4 => 
      array (
        'ContentFieldID' => '4',
        'TableID' => '1',
        'FieldTitle' => '新闻图片',
        'FieldName' => 'Photo',
        'FieldType' => 'varchar',
        'FieldSize' => '250',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => 'upload',
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '3',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '0',
        'EnablePublish' => '1',
      ),
      5 => 
      array (
        'ContentFieldID' => '6',
        'TableID' => '1',
        'FieldTitle' => '新闻内容',
        'FieldName' => 'Content',
        'FieldType' => 'longtext',
        'FieldSize' => NULL,
        'FieldInput' => 'RichEditor',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '4',
        'FieldListDisplay' => '0',
        'IsMainField' => '1',
        'IsTitleField' => '0',
        'FieldSearchable' => '1',
        'EnableContribution' => '0',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      6 => 
      array (
        'ContentFieldID' => '7',
        'TableID' => '1',
        'FieldTitle' => '关键字',
        'FieldName' => 'Keywords',
        'FieldType' => 'varchar',
        'FieldSize' => '250',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '5',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '1',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      7 => 
      array (
        'ContentFieldID' => '5',
        'TableID' => '1',
        'FieldTitle' => '副标题',
        'FieldName' => 'SubTitle',
        'FieldType' => 'varchar',
        'FieldSize' => '250',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '6',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '1',
        'EnableContribution' => '1',
        'EnableCollection' => '0',
        'EnablePublish' => '0',
      ),
      8 => 
      array (
        'ContentFieldID' => '8',
        'TableID' => '1',
        'FieldTitle' => '来源网站',
        'FieldName' => 'FromSite',
        'FieldType' => 'varchar',
        'FieldSize' => '250',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '7',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '1',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      9 => 
      array (
        'ContentFieldID' => '3',
        'TableID' => '1',
        'FieldTitle' => '责任编辑',
        'FieldName' => 'Editor',
        'FieldType' => 'varchar',
        'FieldSize' => '20',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => '新闻编辑',
        'FieldOrder' => '8',
        'FieldListDisplay' => '1',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '1',
        'EnableContribution' => '1',
        'EnableCollection' => '0',
        'EnablePublish' => '1',
      ),
      10 => 
      array (
        'ContentFieldID' => '21',
        'TableID' => '1',
        'FieldTitle' => '自定义相关文章',
        'FieldName' => 'CustomLinks',
        'FieldType' => 'contentlink',
        'FieldSize' => NULL,
        'FieldInput' => 'select',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '9',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '0',
        'EnableCollection' => '0',
        'EnablePublish' => '0',
      ),
      11 => 
      array (
        'ContentFieldID' => '9',
        'TableID' => '1',
        'FieldTitle' => '简介',
        'FieldName' => 'Intro',
        'FieldType' => 'text',
        'FieldSize' => NULL,
        'FieldInput' => 'textaera',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '10',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '1',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
    ),
    'MainField' => 'Content',
  ),
  2 => 
  array (
    'TableID' => '2',
    'Name' => '下载系统模型',
    'DSNID' => '1',
    'TitleField' => 'SoftName',
    'Model' => 
    array (
      0 => 
      array (
        'ContentFieldID' => '18',
        'TableID' => '2',
        'FieldTitle' => '软件名称',
        'FieldName' => 'SoftName',
        'FieldType' => 'varchar',
        'FieldSize' => '250',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '0',
        'FieldListDisplay' => '1',
        'IsMainField' => '0',
        'IsTitleField' => '1',
        'FieldSearchable' => '1',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      1 => 
      array (
        'ContentFieldID' => '22',
        'TableID' => '2',
        'FieldTitle' => '界面预览',
        'FieldName' => 'Photo',
        'FieldType' => 'varchar',
        'FieldSize' => '250',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => 'upload',
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '1',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '1',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      2 => 
      array (
        'ContentFieldID' => '23',
        'TableID' => '2',
        'FieldTitle' => '本地上传',
        'FieldName' => 'LocalUpload',
        'FieldType' => 'varchar',
        'FieldSize' => '250',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => 'upload_attach',
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '2',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '1',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      3 => 
      array (
        'ContentFieldID' => '15',
        'TableID' => '2',
        'FieldTitle' => '软件类别',
        'FieldName' => 'SoftType',
        'FieldType' => 'varchar',
        'FieldSize' => '50',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '3',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '1',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      4 => 
      array (
        'ContentFieldID' => '17',
        'TableID' => '2',
        'FieldTitle' => '软件大小',
        'FieldName' => 'SoftSize',
        'FieldType' => 'varchar',
        'FieldSize' => '250',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '4',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '1',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      5 => 
      array (
        'ContentFieldID' => '16',
        'TableID' => '2',
        'FieldTitle' => '软件语言',
        'FieldName' => 'Language',
        'FieldType' => 'varchar',
        'FieldSize' => '10',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '5',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '1',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      6 => 
      array (
        'ContentFieldID' => '14',
        'TableID' => '2',
        'FieldTitle' => '运行环境',
        'FieldName' => 'Environment',
        'FieldType' => 'varchar',
        'FieldSize' => '50',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '6',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '1',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      7 => 
      array (
        'ContentFieldID' => '13',
        'TableID' => '2',
        'FieldTitle' => '软件评级',
        'FieldName' => 'Star',
        'FieldType' => 'varchar',
        'FieldSize' => '250',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '7',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '1',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      8 => 
      array (
        'ContentFieldID' => '20',
        'TableID' => '2',
        'FieldTitle' => '软件关键字',
        'FieldName' => 'SoftKeywords',
        'FieldType' => 'varchar',
        'FieldSize' => '250',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '8',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '1',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      9 => 
      array (
        'ContentFieldID' => '12',
        'TableID' => '2',
        'FieldTitle' => '开 发 商',
        'FieldName' => 'Developer',
        'FieldType' => 'varchar',
        'FieldSize' => '250',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '9',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '1',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      10 => 
      array (
        'ContentFieldID' => '11',
        'TableID' => '2',
        'FieldTitle' => '软件介绍',
        'FieldName' => 'Intro',
        'FieldType' => 'text',
        'FieldSize' => NULL,
        'FieldInput' => 'RichEditor',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '10',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '1',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      11 => 
      array (
        'ContentFieldID' => '19',
        'TableID' => '2',
        'FieldTitle' => '下载地址',
        'FieldName' => 'Download',
        'FieldType' => 'text',
        'FieldSize' => NULL,
        'FieldInput' => 'textaera',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '11',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '1',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      12 => 
      array (
        'ContentFieldID' => '24',
        'TableID' => '2',
        'FieldTitle' => '自定义相关软件',
        'FieldName' => 'CustomSoftLinks',
        'FieldType' => 'contentlink',
        'FieldSize' => '250',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '12',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      13 => 
      array (
        'ContentFieldID' => '25',
        'TableID' => '2',
        'FieldTitle' => '自定义相关文章',
        'FieldName' => 'CustomLinks',
        'FieldType' => 'contentlink',
        'FieldSize' => '250',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '13',
        'FieldListDisplay' => '0',
        'IsMainField' => '1',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
    ),
    'MainField' => 'CustomLinks',
  ),
  30 => 
  array (
    'TableID' => '30',
    'Name' => '友情链接模型',
    'DSNID' => '0',
    'Model' => 
    array (
      0 => 
      array (
        'ContentFieldID' => '26',
        'TableID' => '30',
        'FieldTitle' => '链接位置',
        'FieldName' => 'Fadd',
        'FieldType' => 'varchar',
        'FieldSize' => '1',
        'FieldInput' => 'select',
        'FieldDefaultValue' => '3;2;1',
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '0',
        'FieldListDisplay' => '1',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '0',
        'EnablePublish' => '1',
        'selectValue' => 
        array (
          0 => '3',
          1 => '2',
          2 => '1',
        ),
      ),
      1 => 
      array (
        'ContentFieldID' => '27',
        'TableID' => '30',
        'FieldTitle' => '链接分类',
        'FieldName' => 'linkClass',
        'FieldType' => 'varchar',
        'FieldSize' => '20',
        'FieldInput' => 'select',
        'FieldDefaultValue' => '服装类;化妆品类;美容机构;感谢站点;合作站点',
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '0',
        'FieldListDisplay' => '1',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '0',
        'EnablePublish' => '1',
        'selectValue' => 
        array (
          0 => '服装类',
          1 => '化妆品类',
          2 => '美容机构',
          3 => '感谢站点',
          4 => '合作站点',
        ),
      ),
      2 => 
      array (
        'ContentFieldID' => '28',
        'TableID' => '30',
        'FieldTitle' => '友情标题',
        'FieldName' => 'FTitle',
        'FieldType' => 'varchar',
        'FieldSize' => '50',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '0',
        'FieldListDisplay' => '1',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '0',
        'EnablePublish' => '1',
      ),
      3 => 
      array (
        'ContentFieldID' => '29',
        'TableID' => '30',
        'FieldTitle' => '友情链接地址',
        'FieldName' => 'FUrl',
        'FieldType' => 'varchar',
        'FieldSize' => '80',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '0',
        'FieldListDisplay' => '1',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '0',
        'EnablePublish' => '1',
      ),
      4 => 
      array (
        'ContentFieldID' => '30',
        'TableID' => '30',
        'FieldTitle' => '友情图片',
        'FieldName' => 'FPhoto',
        'FieldType' => 'varchar',
        'FieldSize' => '100',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '0',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '0',
        'EnablePublish' => '1',
      ),
      5 => 
      array (
        'ContentFieldID' => '31',
        'TableID' => '30',
        'FieldTitle' => '友情链接说明',
        'FieldName' => 'FIntro',
        'FieldType' => 'varchar',
        'FieldSize' => '250',
        'FieldInput' => 'textaera',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '0',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '0',
        'EnablePublish' => '1',
      ),
    ),
  ),
  6 => 
  array (
    'TableID' => '6',
    'Name' => '图片系统模型',
    'DSNID' => '0',
    'Model' => 
    array (
      0 => 
      array (
        'ContentFieldID' => '35',
        'TableID' => '6',
        'FieldTitle' => '图片地址',
        'FieldName' => 'PhotoURL',
        'FieldType' => 'varchar',
        'FieldSize' => '250',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => 'upload',
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '0',
        'FieldListDisplay' => '1',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      1 => 
      array (
        'ContentFieldID' => '34',
        'TableID' => '6',
        'FieldTitle' => '图片名称',
        'FieldName' => 'PhotoName',
        'FieldType' => 'varchar',
        'FieldSize' => '250',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '0',
        'FieldListDisplay' => '1',
        'IsMainField' => '0',
        'IsTitleField' => '1',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      2 => 
      array (
        'ContentFieldID' => '36',
        'TableID' => '6',
        'FieldTitle' => '图片简介',
        'FieldName' => 'PhotoIntro',
        'FieldType' => 'text',
        'FieldSize' => NULL,
        'FieldInput' => 'RichEditor',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '0',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      3 => 
      array (
        'ContentFieldID' => '37',
        'TableID' => '6',
        'FieldTitle' => '图片标注',
        'FieldName' => 'alt',
        'FieldType' => 'varchar',
        'FieldSize' => '250',
        'FieldInput' => 'textaera',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '0',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
    ),
    'TitleField' => 'PhotoName',
  ),
  5 => 
  array (
    'TableID' => '5',
    'Name' => '影视系统模型',
    'DSNID' => '0',
    'TitleField' => 'Title',
    'Model' => 
    array (
      0 => 
      array (
        'ContentFieldID' => '38',
        'TableID' => '5',
        'FieldTitle' => '电影名称',
        'FieldName' => 'Title',
        'FieldType' => 'varchar',
        'FieldSize' => '250',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '0',
        'FieldListDisplay' => '1',
        'IsMainField' => '0',
        'IsTitleField' => '1',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      1 => 
      array (
        'ContentFieldID' => '39',
        'TableID' => '5',
        'FieldTitle' => '英文名称',
        'FieldName' => 'EnName',
        'FieldType' => 'varchar',
        'FieldSize' => '250',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '1',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      2 => 
      array (
        'ContentFieldID' => '40',
        'TableID' => '5',
        'FieldTitle' => '上映日期',
        'FieldName' => 'Show',
        'FieldType' => 'varchar',
        'FieldSize' => '250',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => 'date',
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '2',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      3 => 
      array (
        'ContentFieldID' => '41',
        'TableID' => '5',
        'FieldTitle' => '剧照',
        'FieldName' => 'Photo',
        'FieldType' => 'varchar',
        'FieldSize' => '250',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => 'upload',
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '3',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      4 => 
      array (
        'ContentFieldID' => '42',
        'TableID' => '5',
        'FieldTitle' => '类型',
        'FieldName' => 'Style',
        'FieldType' => 'text',
        'FieldSize' => '250',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '4',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      5 => 
      array (
        'ContentFieldID' => '43',
        'TableID' => '5',
        'FieldTitle' => '导演',
        'FieldName' => 'Director',
        'FieldType' => 'varchar',
        'FieldSize' => '250',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '5',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      6 => 
      array (
        'ContentFieldID' => '44',
        'TableID' => '5',
        'FieldTitle' => '主演',
        'FieldName' => 'Player',
        'FieldType' => 'varchar',
        'FieldSize' => '250',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '6',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      7 => 
      array (
        'ContentFieldID' => '45',
        'TableID' => '5',
        'FieldTitle' => '推荐指数',
        'FieldName' => 'Comm',
        'FieldType' => 'varchar',
        'FieldSize' => '250',
        'FieldInput' => 'text',
        'FieldDefaultValue' => '★;★★;★★★;★★★★;★★★★★',
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '7',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
        'selectValue' => 
        array (
          0 => '★',
          1 => '★★',
          2 => '★★★',
          3 => '★★★★',
          4 => '★★★★★',
        ),
      ),
      8 => 
      array (
        'ContentFieldID' => '46',
        'TableID' => '5',
        'FieldTitle' => '剧情看点',
        'FieldName' => 'Watch',
        'FieldType' => 'mediumtext',
        'FieldSize' => NULL,
        'FieldInput' => 'textaera',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '8',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      9 => 
      array (
        'ContentFieldID' => '47',
        'TableID' => '5',
        'FieldTitle' => '剧情介绍',
        'FieldName' => 'Content',
        'FieldType' => 'longtext',
        'FieldSize' => NULL,
        'FieldInput' => 'RichEditor',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '9',
        'FieldListDisplay' => '0',
        'IsMainField' => '1',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      10 => 
      array (
        'ContentFieldID' => '48',
        'TableID' => '5',
        'FieldTitle' => '在线地址',
        'FieldName' => 'OnLine',
        'FieldType' => 'mediumtext',
        'FieldSize' => NULL,
        'FieldInput' => 'textaera',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '10',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      11 => 
      array (
        'ContentFieldID' => '49',
        'TableID' => '5',
        'FieldTitle' => '下载地址',
        'FieldName' => 'Down',
        'FieldType' => 'mediumtext',
        'FieldSize' => NULL,
        'FieldInput' => 'textaera',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '11',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      12 => 
      array (
        'ContentFieldID' => '50',
        'TableID' => '5',
        'FieldTitle' => 'p2p播放',
        'FieldName' => 'p2pPlay',
        'FieldType' => 'mediumtext',
        'FieldSize' => NULL,
        'FieldInput' => 'textaera',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '12',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
    ),
    'MainField' => 'Content',
  ),
  31 => 
  array (
    'TableID' => '31',
    'Name' => '百问系统模型',
    'DSNID' => '0',
    'Model' => 
    array (
      0 => 
      array (
        'ContentFieldID' => '51',
        'TableID' => '31',
        'FieldTitle' => '标题',
        'FieldName' => 'com_title',
        'FieldType' => 'varchar',
        'FieldSize' => '250',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => 'notnull',
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => '问题标题',
        'FieldOrder' => '0',
        'FieldListDisplay' => '1',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      1 => 
      array (
        'ContentFieldID' => '52',
        'TableID' => '31',
        'FieldTitle' => '内容',
        'FieldName' => 'com_content',
        'FieldType' => 'text',
        'FieldSize' => NULL,
        'FieldInput' => 'textaera',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => '问题详情',
        'FieldOrder' => '0',
        'FieldListDisplay' => '0',
        'IsMainField' => '1',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      2 => 
      array (
        'ContentFieldID' => '53',
        'TableID' => '31',
        'FieldTitle' => '用户id',
        'FieldName' => 'userId',
        'FieldType' => 'varchar',
        'FieldSize' => '250',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => '用户id',
        'FieldOrder' => '0',
        'FieldListDisplay' => '1',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      3 => 
      array (
        'ContentFieldID' => '61',
        'TableID' => '31',
        'FieldTitle' => '用户名',
        'FieldName' => 'userName',
        'FieldType' => 'varchar',
        'FieldSize' => '50',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '0',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      4 => 
      array (
        'ContentFieldID' => '55',
        'TableID' => '31',
        'FieldTitle' => '内容id',
        'FieldName' => 'ids',
        'FieldType' => 'varchar',
        'FieldSize' => '250',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => 'num',
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '0',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      5 => 
      array (
        'ContentFieldID' => '60',
        'TableID' => '31',
        'FieldTitle' => '最佳答案id',
        'FieldName' => 'BestID',
        'FieldType' => 'int',
        'FieldSize' => '10',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => 'num',
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '0',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
    ),
    'MainField' => 'com_content',
  ),
  51 => 
  array (
    'TableID' => '51',
    'Name' => '自动回复语句',
    'DSNID' => '0',
    'Model' => 
    array (
      0 => 
      array (
        'ContentFieldID' => '63',
        'TableID' => '51',
        'FieldTitle' => '自动回复用于',
        'FieldName' => 'words',
        'FieldType' => 'text',
        'FieldSize' => '250',
        'FieldInput' => 'textaera',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '0',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
    ),
  ),
);
?>