<?php
//CMS cache file, DO NOT modify me!
//Created on July 16, 2010, 12:19

$NODE_LIST = array (
  6 => 
  array (
    'NodeID' => '6',
    'Name' => '影像艺术',
    'ParentID' => '0',
    'TableID' => '1',
    'PublishMode' => '1',
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '17',
  ),
  7 => 
  array (
    'NodeID' => '7',
    'Name' => '秀色可餐',
    'ParentID' => '6',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  91 => 
  array (
    'NodeID' => '91',
    'Name' => '美女摄影',
    'ParentID' => '6',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  132 => 
  array (
    'NodeID' => '132',
    'Name' => '明星写真',
    'ParentID' => '6',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  133 => 
  array (
    'NodeID' => '133',
    'Name' => '手机背景',
    'ParentID' => '6',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  142 => 
  array (
    'NodeID' => '142',
    'Name' => '美丽百问',
    'ParentID' => '0',
    'TableID' => '31',
    'PublishMode' => '2',
    'NodeType' => '1',
    'WorkFlow' => '4',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '18',
  ),
  143 => 
  array (
    'NodeID' => '143',
    'Name' => '面部护肤',
    'ParentID' => '142',
    'TableID' => '31',
    'PublishMode' => '2',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '4',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  144 => 
  array (
    'NodeID' => '144',
    'Name' => '美发护发',
    'ParentID' => '143',
    'TableID' => '31',
    'PublishMode' => '2',
    'cHeader' => 2,
    'NodeType' => '1',
    'WorkFlow' => '4',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  145 => 
  array (
    'NodeID' => '145',
    'Name' => '美发护发',
    'ParentID' => '142',
    'TableID' => '31',
    'PublishMode' => '2',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '4',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  146 => 
  array (
    'NodeID' => '146',
    'Name' => '瘦身美体',
    'ParentID' => '142',
    'TableID' => '31',
    'PublishMode' => '2',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '4',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  147 => 
  array (
    'NodeID' => '147',
    'Name' => '时尚彩妆',
    'ParentID' => '142',
    'TableID' => '31',
    'PublishMode' => '2',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '4',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  148 => 
  array (
    'NodeID' => '148',
    'Name' => '搭配日记',
    'ParentID' => '142',
    'TableID' => '31',
    'PublishMode' => '2',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '4',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  191 => 
  array (
    'NodeID' => '191',
    'Name' => '娱乐游戏',
    'ParentID' => '0',
    'TableID' => '1',
    'PublishMode' => '1',
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => 'yulexinwen',
    'NodeClassMark' => NULL,
    'NodeSort' => '18',
  ),
  186 => 
  array (
    'NodeID' => '186',
    'Name' => '游戏',
    'ParentID' => '191',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '4',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  70 => 
  array (
    'NodeID' => '70',
    'Name' => '完美世界国际版',
    'ParentID' => '186',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 2,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  187 => 
  array (
    'NodeID' => '187',
    'Name' => '魔兽世界',
    'ParentID' => '186',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 2,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  188 => 
  array (
    'NodeID' => '188',
    'Name' => '地下城与勇士',
    'ParentID' => '186',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 2,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  189 => 
  array (
    'NodeID' => '189',
    'Name' => '武林英雄',
    'ParentID' => '186',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 2,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  190 => 
  array (
    'NodeID' => '190',
    'Name' => '网络游戏',
    'ParentID' => '186',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 2,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  192 => 
  array (
    'NodeID' => '192',
    'Name' => '电影',
    'ParentID' => '191',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  193 => 
  array (
    'NodeID' => '193',
    'Name' => '明星八卦',
    'ParentID' => '191',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  195 => 
  array (
    'NodeID' => '195',
    'Name' => '音乐',
    'ParentID' => '191',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  215 => 
  array (
    'NodeID' => '215',
    'Name' => '网络常用',
    'ParentID' => '191',
    'TableID' => '51',
    'PublishMode' => '0',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  56 => 
  array (
    'NodeID' => '56',
    'Name' => '丰胸瘦身',
    'ParentID' => '0',
    'TableID' => '1',
    'PublishMode' => '1',
    'NodeType' => '1',
    'WorkFlow' => '4',
    'NodeGUID' => '',
    'NodeClassMark' => NULL,
    'NodeSort' => '19',
  ),
  5 => 
  array (
    'NodeID' => '5',
    'Name' => '美丽塑造',
    'ParentID' => '56',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  57 => 
  array (
    'NodeID' => '57',
    'Name' => '丰胸',
    'ParentID' => '56',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  58 => 
  array (
    'NodeID' => '58',
    'Name' => '腰腹减肥',
    'ParentID' => '56',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  59 => 
  array (
    'NodeID' => '59',
    'Name' => '翘臀细臂',
    'ParentID' => '56',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  60 => 
  array (
    'NodeID' => '60',
    'Name' => '美腿',
    'ParentID' => '56',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  62 => 
  array (
    'NodeID' => '62',
    'Name' => '小脸',
    'ParentID' => '56',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  120 => 
  array (
    'NodeID' => '120',
    'Name' => '生活情趣',
    'ParentID' => '0',
    'TableID' => '1',
    'PublishMode' => '1',
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '20',
  ),
  104 => 
  array (
    'NodeID' => '104',
    'Name' => '性爱笔记',
    'ParentID' => '120',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  121 => 
  array (
    'NodeID' => '121',
    'Name' => '欲望城市',
    'ParentID' => '120',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  122 => 
  array (
    'NodeID' => '122',
    'Name' => '单身日记',
    'ParentID' => '120',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  89 => 
  array (
    'NodeID' => '89',
    'Name' => '营养顾问',
    'ParentID' => '120',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '4',
  ),
  85 => 
  array (
    'NodeID' => '85',
    'Name' => '理财',
    'ParentID' => '120',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '5',
  ),
  88 => 
  array (
    'NodeID' => '88',
    'Name' => '情趣DIY',
    'ParentID' => '120',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '6',
  ),
  131 => 
  array (
    'NodeID' => '131',
    'Name' => '家常菜谱',
    'ParentID' => '120',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '6',
  ),
  206 => 
  array (
    'NodeID' => '206',
    'Name' => '亲子',
    'ParentID' => '0',
    'TableID' => '1',
    'PublishMode' => '1',
    'NodeType' => '1',
    'WorkFlow' => '4',
    'NodeGUID' => '',
    'NodeClassMark' => NULL,
    'NodeSort' => '22',
  ),
  208 => 
  array (
    'NodeID' => '208',
    'Name' => '辅食',
    'ParentID' => '206',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '1',
  ),
  211 => 
  array (
    'NodeID' => '211',
    'Name' => '育儿',
    'ParentID' => '206',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '2',
  ),
  210 => 
  array (
    'NodeID' => '210',
    'Name' => '早教',
    'ParentID' => '206',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '3',
  ),
  209 => 
  array (
    'NodeID' => '209',
    'Name' => '宝宝',
    'ParentID' => '206',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '4',
  ),
  212 => 
  array (
    'NodeID' => '212',
    'Name' => '奶粉',
    'ParentID' => '209',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 2,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  213 => 
  array (
    'NodeID' => '213',
    'Name' => '营养品',
    'ParentID' => '209',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 2,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  214 => 
  array (
    'NodeID' => '214',
    'Name' => '纸尿裤',
    'ParentID' => '209',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 2,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  207 => 
  array (
    'NodeID' => '207',
    'Name' => '怀孕',
    'ParentID' => '206',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '5',
  ),
  180 => 
  array (
    'NodeID' => '180',
    'Name' => '美丽报告',
    'ParentID' => '0',
    'TableID' => '1',
    'PublishMode' => '1',
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '25',
  ),
  23 => 
  array (
    'NodeID' => '23',
    'Name' => '美白护肤',
    'ParentID' => '0',
    'TableID' => '1',
    'PublishMode' => '1',
    'NodeType' => '1',
    'WorkFlow' => '4',
    'NodeGUID' => '',
    'NodeClassMark' => NULL,
    'NodeSort' => '26',
  ),
  28 => 
  array (
    'NodeID' => '28',
    'Name' => '美白',
    'ParentID' => '23',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  29 => 
  array (
    'NodeID' => '29',
    'Name' => '面部保湿',
    'ParentID' => '23',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  30 => 
  array (
    'NodeID' => '30',
    'Name' => '防晒',
    'ParentID' => '23',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  33 => 
  array (
    'NodeID' => '33',
    'Name' => '洁面',
    'ParentID' => '23',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  35 => 
  array (
    'NodeID' => '35',
    'Name' => '追击祛斑',
    'ParentID' => '23',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  36 => 
  array (
    'NodeID' => '36',
    'Name' => '眼部护理',
    'ParentID' => '23',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  119 => 
  array (
    'NodeID' => '119',
    'Name' => '美丽法则',
    'ParentID' => '23',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  79 => 
  array (
    'NodeID' => '79',
    'Name' => '护理',
    'ParentID' => '23',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '8',
  ),
  32 => 
  array (
    'NodeID' => '32',
    'Name' => '控油',
    'ParentID' => '23',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '9',
  ),
  31 => 
  array (
    'NodeID' => '31',
    'Name' => '祛痘',
    'ParentID' => '23',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '10',
  ),
  37 => 
  array (
    'NodeID' => '37',
    'Name' => '黑头',
    'ParentID' => '23',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '11',
  ),
  34 => 
  array (
    'NodeID' => '34',
    'Name' => '毛孔',
    'ParentID' => '23',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '12',
  ),
  90 => 
  array (
    'NodeID' => '90',
    'Name' => '抗皱',
    'ParentID' => '23',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '13',
  ),
  24 => 
  array (
    'NodeID' => '24',
    'Name' => '化妆',
    'ParentID' => '0',
    'TableID' => '1',
    'PublishMode' => '1',
    'NodeType' => '1',
    'WorkFlow' => '4',
    'NodeGUID' => '',
    'NodeClassMark' => NULL,
    'NodeSort' => '28',
  ),
  38 => 
  array (
    'NodeID' => '38',
    'Name' => '彩妆趋势',
    'ParentID' => '24',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  39 => 
  array (
    'NodeID' => '39',
    'Name' => '教你化妆',
    'ParentID' => '24',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  46 => 
  array (
    'NodeID' => '46',
    'Name' => '烟熏妆',
    'ParentID' => '24',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  107 => 
  array (
    'NodeID' => '107',
    'Name' => '化妆品',
    'ParentID' => '24',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  40 => 
  array (
    'NodeID' => '40',
    'Name' => '技巧',
    'ParentID' => '24',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '5',
  ),
  44 => 
  array (
    'NodeID' => '44',
    'Name' => '宴会妆',
    'ParentID' => '24',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '6',
  ),
  42 => 
  array (
    'NodeID' => '42',
    'Name' => '晚妆',
    'ParentID' => '24',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '7',
  ),
  43 => 
  array (
    'NodeID' => '43',
    'Name' => '透明妆',
    'ParentID' => '24',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '8',
  ),
  45 => 
  array (
    'NodeID' => '45',
    'Name' => '职业妆',
    'ParentID' => '24',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '9',
  ),
  41 => 
  array (
    'NodeID' => '41',
    'Name' => '日妆',
    'ParentID' => '24',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '10',
  ),
  25 => 
  array (
    'NodeID' => '25',
    'Name' => '发型',
    'ParentID' => '0',
    'TableID' => '1',
    'PublishMode' => '1',
    'NodeType' => '1',
    'WorkFlow' => '4',
    'NodeGUID' => '',
    'NodeClassMark' => NULL,
    'NodeSort' => '30',
  ),
  48 => 
  array (
    'NodeID' => '48',
    'Name' => '美发基础',
    'ParentID' => '25',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  151 => 
  array (
    'NodeID' => '151',
    'Name' => '发品使用',
    'ParentID' => '48',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 2,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  152 => 
  array (
    'NodeID' => '152',
    'Name' => '发具用法',
    'ParentID' => '48',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 2,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  153 => 
  array (
    'NodeID' => '153',
    'Name' => '头发护理',
    'ParentID' => '48',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 2,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  129 => 
  array (
    'NodeID' => '129',
    'Name' => '新娘发型',
    'ParentID' => '25',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  203 => 
  array (
    'NodeID' => '203',
    'Name' => '美发店',
    'ParentID' => '25',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  204 => 
  array (
    'NodeID' => '204',
    'Name' => '发型师',
    'ParentID' => '25',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  141 => 
  array (
    'NodeID' => '141',
    'Name' => '发饰',
    'ParentID' => '25',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '1',
  ),
  53 => 
  array (
    'NodeID' => '53',
    'Name' => '束发',
    'ParentID' => '25',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '4',
  ),
  50 => 
  array (
    'NodeID' => '50',
    'Name' => '直发',
    'ParentID' => '25',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '5',
  ),
  49 => 
  array (
    'NodeID' => '49',
    'Name' => '时尚发型',
    'ParentID' => '25',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '9',
  ),
  47 => 
  array (
    'NodeID' => '47',
    'Name' => '流行发型',
    'ParentID' => '25',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '10',
  ),
  128 => 
  array (
    'NodeID' => '128',
    'Name' => '非主流',
    'ParentID' => '25',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '10',
  ),
  126 => 
  array (
    'NodeID' => '126',
    'Name' => '发型diy',
    'ParentID' => '25',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '11',
  ),
  55 => 
  array (
    'NodeID' => '55',
    'Name' => '刘海',
    'ParentID' => '25',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '12',
  ),
  51 => 
  array (
    'NodeID' => '51',
    'Name' => '卷发',
    'ParentID' => '25',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '13',
  ),
  54 => 
  array (
    'NodeID' => '54',
    'Name' => '短发',
    'ParentID' => '25',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '14',
  ),
  52 => 
  array (
    'NodeID' => '52',
    'Name' => '盘发',
    'ParentID' => '25',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '15',
  ),
  1 => 
  array (
    'NodeID' => '1',
    'Name' => '首页',
    'ParentID' => '0',
    'TableID' => '1',
    'PublishMode' => '1',
    'NodeType' => '1',
    'WorkFlow' => '4',
    'NodeGUID' => 'shouye',
    'NodeClassMark' => NULL,
    'NodeSort' => '255',
  ),
  100 => 
  array (
    'NodeID' => '100',
    'Name' => '友情链接',
    'ParentID' => '1',
    'TableID' => '30',
    'PublishMode' => '1',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  3 => 
  array (
    'NodeID' => '3',
    'Name' => '穿衣打扮',
    'ParentID' => '0',
    'TableID' => '1',
    'PublishMode' => '1',
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => 'shishang',
    'NodeClassMark' => NULL,
    'NodeSort' => '255',
  ),
  118 => 
  array (
    'NodeID' => '118',
    'Name' => '服装常识',
    'ParentID' => '3',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  178 => 
  array (
    'NodeID' => '178',
    'Name' => '穿衣真经',
    'ParentID' => '3',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '0',
  ),
  205 => 
  array (
    'NodeID' => '205',
    'Name' => '环球',
    'ParentID' => '3',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '3',
  ),
  17 => 
  array (
    'NodeID' => '17',
    'Name' => '饰品',
    'ParentID' => '3',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '4',
  ),
  115 => 
  array (
    'NodeID' => '115',
    'Name' => '职场',
    'ParentID' => '3',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '5',
  ),
  94 => 
  array (
    'NodeID' => '94',
    'Name' => '搭配',
    'ParentID' => '3',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '6',
  ),
  101 => 
  array (
    'NodeID' => '101',
    'Name' => '明星',
    'ParentID' => '3',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '7',
  ),
  105 => 
  array (
    'NodeID' => '105',
    'Name' => '流行',
    'ParentID' => '3',
    'TableID' => '1',
    'PublishMode' => '1',
    'cHeader' => 1,
    'NodeType' => '1',
    'WorkFlow' => '0',
    'NodeGUID' => NULL,
    'NodeClassMark' => NULL,
    'NodeSort' => '8',
  ),
);
?>