<?php
//CMS cache file, DO NOT modify me!
//Created on July 20, 2010, 16:41

$SYS_ENV = array (
  'backupPath' => '../backup',
  'hostname' => NULL,
  'sysname' => 'http://oecsh.cn/cms/',
  'version' => 'CMSware 2.5 Plus Stable',
  'templatePath' => '../../templates/sesoe/',
  'smtp_host' => '',
  'smtp_username' => '',
  'smtp_password' => '',
  'smtp_from_email' => NULL,
  'smtp_auth' => '',
  'upImgType' => 'png|gif|jpeg|jpg|bmp',
  'upImgSize' => '10000',
  'upAttachType' => 'zip|rar|doc|xls|txt|pdf|pptx|ppt|jpg|png|gif|jpeg|bmp',
  'upAttachSize' => '20000',
  'tasktimeout' => '',
  'sitename' => NULL,
  'uploadPath' => NULL,
  'ResourceNum' => '25892',
  'upload_flash_num' => '68',
  'upload_attach_num' => '44',
  'uploadUrl' => NULL,
  'upFlashSize' => '10000',
  'openTask' => '',
  'ResourcePath' => '../resource',
  'localImgIgnoreURL' => '{localhost}{127.0.0.1}{sesoe.com}',
  'publishResourceNum' => '51588',
  'is_safe_mode' => '',
  'ftp_server' => '',
  'ftp_server_port' => '',
  'ftp_user_name' => '',
  'ftp_user_pass' => '',
  'ftp_cms_admin_path' => '',
  'language' => '',
  'DisplayNodeID' => '1',
  'CollectionPageNum' => '50',
  'ContentPageNum' => '50',
  'SearchPageNum' => '50',
  'sessionTimeout' => '120',
  'isLogLogin' => '1',
  'isLogAdmin' => '1',
  'DisplayPublishCount' => '1',
  'LoginTryTime' => '15',
  'LoginTryCount' => '5',
  'enable_gzip' => '0',
  'AutoPageLen' => '2000',
  'EnableWaterMark' => '0',
  'WaterMarkImgPath' => '../html/WaterMark.png',
  'WaterMarkPosition' => '9',
  'EnableCLWaterMark' => '1',
  'ContentViewMode' => '1',
  'CollectionViewMode' => '1',
  'ContributionViewMode' => '1',
  'DefaultResourcePSN' => '',
  'DefaultResourcePSNURL' => '',
  'DefaultContentPSN' => '',
  'DefaultContentPSNURL' => '',
  'DialogFitXP' => '1',
  'EnableEditorWaterMark' => '1',
  'AutoRefreshTree' => '1',
);
?>